<a href="https://colab.research.google.com/github/redinbluesky/fun-coding-python-data-analysis/blob/main/10-마케팅_데이터_분석하기.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  목차
* [Chapter 10-1 데이터 불러와 확인하기](#chapter10-1)
    * [Chapter 10-1-1 데이터 구조 파악하기](#chapter10-1-1)
    * [Chapter 10-1-2 기본 통계 정보 확인하기](#chapter10-1-2)
* [Chapter 10-2 데이터 분석하기](#chapter10-2)    
    * [Chapter 10-2-1 데이터 전처리 하기](#chapter10-2-1)    
    * [Chapter 10-2-2 마케팅 채널별 고객 획득 비용 분석하기](#chapter10-2-2)  
    * [Chapter 10-2-3 마케팅 채널별 평균 구매 전환율 분석하기](#chapter10-2-3)  
    * [Chapter 10-2-4 타깃 고객 그룹별 평균 구매 전환율 분석하기](#chapter10-2-4)  
    * [Chapter 10-2-5 캠페인 기간별 구매 전환율 분석하기](#chapter10-2-5)  
    * [Chapter 10-2-6 지역별 고객 획득 비용 분석하기](#chapter10-2-6)  
    * [Chapter 10-2-7 종합 분석하기](#chapter10-2-7)  
* [Chapter 10-3 데이터 시각화하기](#chapter10-3)

## Chapter 10-1 데이터 불러와 확인하기 <a class="anchor" id="chapter10-1"></a>
1. 
 파일을 불러와 사용한다.
    - 케글에서 제공하는 데이터 셋으로 2년에 걸쳐 수집된 200.000건의 마켓팅 캠페인 성과 데이터이다.

### Chapter 10-1-1 데이터 구조 파악하기 <a class="anchor" id="chapter10-1-1"></a>
1. marketing_campaign_dataset.csv 파일의 컬럼 확인
    - 인덱스: 데이터 프레임의 인덱스를 나타내며 0부터 시작한다.
    - Campaign_ID: 각 마케팅 캠페인의 고유 식별자이다.
    - Company: 마케팅 캠페인을 진행한 회사의 이름이다.
    - Campaign_Type: 마케팅 캠페인의 유형을 나타내며, 예를 들어 이메일, 소셜 미디어, TV 광고 등이 있다.
    - Target_Audience: 마케팅 캠페인의 타겟 오디언스를 나타내며, 예를 들어 남자 20-30세, 여자 30-40세 등이 있다.
    - Duration: 마케팅 캠페인의 기간을 나타내며, 예를 들어 30일, 60일 등이 있다.
    - Cnannel_Used: 마케팅 캠페인에서 사용된 채널을 나타내며, 예를 들어 이메일, 소셜 미디어, TV 광고 등이 있다.
    - Conversion_Rate: 마케팅 캠페인의 전환율을 나타내며, 예를 들어 0.05는 5%의 전환율을 의미한다.
    - Acquisition_Cost: 마케팅 캠페인에서 고객 한 명을 획득하는 데 드는 비용을 나타내며, 예를 들어 10.0은 고객 한 명을 획득하는 데 10달러가 드는 것을 의미한다.
    - ROI: 마케팅 캠페인의 투자 수익률을 나타내며, 예를 들어 0.2는 20%의 투자 수익률을 의미한다. 
        - 캠페인의 전반적인 성과를 평가하는 지표이다.
    - Location: 마케팅 캠페인이 진행된 위치를 나타내며, 예를 들어 미국, 유럽 등이 있다. 
        - 지역별 마케팅 전략을 평가하는데 사용된다.
    - Language: 마케팅 캠페인이 진행된 언어를 나타내며, 예를 들어 영어, 스페인어 등이 있다. 
        - 현지화 전략을 평가하는데 사용된다.
    - Clicks: 마케팅 캠페인에서 발생한 클릭 수를 나타낸다. 
        - 캠페인의 흥미 유발 정도를 평가한다.
    - Impressions: 마케팅 캠페인에서 발생한 노출 수를 나타낸다. 
        - 캠페인의 도달 범위를 평가하는 지표이다.
    - Engagement_Score: 마케팅 캠페인에서 발생한 참여 점수를 나타내며, 1(참여보 매우 낮음)부터 10(참여도 매우 높음) 사이에서 산출된다.
        - 클릭, 댓글 등 사용자가 캠페인에 얼마나 적극적으로 참여했는지를 평가하는 지표이다.
    - Customer_Segment: 마케팅 캠페인의 고객 세그먼트를 나타내며, 예를 들어 고소득층, 중산층 등이 있다. 
        - 특정 고객 세그먼트에 대한 캠페인 성과를 평가하는데 사용된다.
    - Date: 마케팅 캠페인이 진행된 날짜를 나타낸다. 
        - 시간에 따른 캠페인 성과를 평가하는데 사용된다.

2. 도메인 지식
    - 특정 분야나 산업에 대한 전문적인 이해와 통찰력을 의미한다.
    - 데이터 열의 의미를 명확히 이해하려면 해당 분야에 대한 도메인 지식이 필요하다.
    - 데이터 분석가나 데이터 과학자는 효과적인 분석을 수행하기 위해 도메인 지식을 반드시 갖춰야한다.

In [1]:
# marketing_campaign_dataset.csv 파일 읽어와 크기 확인]
import pandas as pd

df = pd.read_csv('./data/marketing_campaign_dataset.csv')

df.shape

(200000, 16)

In [2]:
# 처음 5개 행 확인
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

In [3]:
# 마지막 5개 행 확인
df.tail()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
199995,199996,TechCorp,Display,All Ages,30 days,Google Ads,0.06,"$18,365.00",2.84,Chicago,German,858,5988,1,Tech Enthusiasts,2021-12-07
199996,199997,DataTech Solutions,Email,Men 25-34,15 days,Facebook,0.02,"$8,168.00",4.14,Chicago,Spanish,228,3068,7,Foodies,2021-12-08
199997,199998,DataTech Solutions,Social Media,Men 18-24,45 days,Website,0.05,"$13,397.00",3.25,New York,Mandarin,723,9548,3,Tech Enthusiasts,2021-12-09
199998,199999,Innovate Industries,Influencer,All Ages,30 days,YouTube,0.10,"$18,508.00",3.86,Houston,French,528,2763,1,Foodies,2021-12-10
199999,200000,Innovate Industries,Social Media,Women 35-44,45 days,Google Ads,0.01,"$13,835.00",6.64,Chicago,Spanish,924,7287,8,Tech Enthusiasts,2021-12-11

### Chapter 10-1-2 기본 통계 정보 확인하기 <a class="anchor" id="chapter10-1-2"></a>

In [4]:
# describe() 메서드를 사용해 기본 통계정보 확인
df.describe()

,Campaign_ID,Conversion_Rate,ROI,Clicks,Impressions,Engagement_Score
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,100000.500000,0.080070,5.002438,549.772030,5507.301520,5.494710
std,57735.171256,0.040602,1.734488,260.019056,2596.864286,2.872581
min,1.000000,0.010000,2.000000,100.000000,1000.000000,1.000000
25%,50000.750000,0.050000,3.500000,325.000000,3266.000000,3.000000
50%,100000.500000,0.080000,5.010000,550.000000,5517.500000,5.000000
75%,150000.250000,0.120000,6.510000,775.000000,7753.000000,8.000000
max,200000.000000,0.150000,8.000000,1000.000000,10000.000000,10.000000

## Chapter 10-2 데이터 분석하기 <a class="anchor" id="chapter10-2"></a>
### Chapter 10-2-1 데이터 전처리하기 <a class="anchor" id="chapter10-2-1"></a>

In [5]:
# 고객 획득비용(Acquisition_Cost) 컬럼 값의 5 개행 출력
df['Acquisition_Cost'].head()

0    $16,174.00
1    $11,566.00
2    $10,200.00
3    $12,724.00
4    $16,452.00
Name: Acquisition_Cost, dtype: str

In [7]:
# 고객 획득비용(Acquisition_Cost) 컬럼의 특수기호 제거 후 float 형으로 변환
df['Acquisition_Cost'] = df['Acquisition_Cost'].str.replace('$','').str.replace(',','').astype(float);

In [8]:
# 총 고객 획득비용 계산
total_acquisition_cost = df['Acquisition_Cost'].sum();
total_acquisition_cost

np.float64(2500878608.0)

### Chapter 10-2-2 마케팅 채널별 고객 획득 비용 분석하기 <a class="anchor" id="chapter10-2-2"></a>

In [10]:
# Channel_Used 컬럼으로 그룹화 후 합계 금액을 구한다.
channel_acquisition_cost = df.groupby('Channel_Used')['Acquisition_Cost'].sum()
print("채널별 고객 획득 비용:")
print(channel_acquisition_cost)

채널별 고객 획득 비용:
Channel_Used
Email         420874104.0
Facebook      410595258.0
Google Ads    418912314.0
Instagram     417124850.0
Website       416593500.0
YouTube       416778582.0
Name: Acquisition_Cost, dtype: float64

In [11]:
# CSV 파일로 저장
channel_acquisition_cost.to_csv('./data/channel_acquisition_cost.csv')

### Chapter 10-2-3 마케팅 채널별 평균 구매 전환율 분석하기 <a class="anchor" id="chapter10-2-3"></a>

In [14]:
# Channel_Used 그룹화 후 Conversion_Rate열의 평균을 계산한다.
channel_conversion_rate = df.groupby('Channel_Used')['Conversion_Rate'].mean()
print("채널별 평균 구매 전환율: ")
print(channel_conversion_rate)

채널별 평균 구매 전환율:
Channel_Used
Email         0.080282
Facebook      0.079992
Google Ads    0.080183
Instagram     0.079886
Website       0.080183
YouTube       0.079889
Name: Conversion_Rate, dtype: float64

In [15]:
# CSV 파일로 저장
channel_conversion_rate.to_csv('./data/channel_conversion_rate.csv')

### Chapter 10-2-4 타깃 고객 그룹별 평균 구매 전황율 분석하기 <a class="anchor" id="chapter10-2-4"></a>

In [16]:
# Target_Audience 열을 기준으로 그룹화 후 Conversion_Rate 열의 평균을 구한다.
audience_conversion_rate = df.groupby('Target_Audience')['Conversion_Rate'].mean()
print("타깃 고객 그룹별 평균 구매 전환율: ")
print(audience_conversion_rate)

타깃 고객 그룹별 평균 구매 전환율:
Target_Audience
All Ages       0.079975
Men 18-24      0.080240
Men 25-34      0.080132
Women 25-34    0.079899
Women 35-44    0.080102
Name: Conversion_Rate, dtype: float64

In [17]:
# CSV 파일로 저장
audience_conversion_rate.to_csv('./data/audience_conversion_rate.csv')

### Chapter 10-2-5 캠페인 기간별 구매 전환율 분석하기 <a class="anchor" id="chapter10-2-5"></a>

In [18]:
# Duration열을 기준으로 그룹화 후 Conversion_Rate 열의 평균 계산
duration_conversion_rate = df.groupby('Duration')['Conversion_Rate'].mean()
print("캠페인 기간별 평균 구매 전환율: ")
print(duration_conversion_rate)

캠페인 기간별 평균 구매 전환율:
Duration
15 days    0.080101
30 days    0.080177
45 days    0.079952
60 days    0.080048
Name: Conversion_Rate, dtype: float64

In [19]:
# CSV 파일로 저장
duration_conversion_rate.to_csv('./data/duration_conversion_rate.csv')

### Chapter 10-2-6 지역별 고객 획득 비용 분석하기 <a class="anchor" id="chapter10-2-6"></a>

In [20]:
# Location 열을 기준으로 그룹화 후 Acauisition_Cost열의 합 구하기
location_acquisition_cost = df.groupby('Location')['Acquisition_Cost'].sum()
print("지역별 고객 획득 비용: ")
print(location_acquisition_cost)

지역별 고객 획득 비용:
Location
Chicago        500731615.0
Houston        495061893.0
Los Angeles    500637366.0
Miami          503974911.0
New York       500472823.0
Name: Acquisition_Cost, dtype: float64

### Chapter 10-2-7 종합 분석하기 <a class="anchor" id="chapter10-2-7"></a>

## Chapter 10-3 데이터 시각화하기 <a class="anchor" id="chapter10-3"></a>